## Eureka Server Registration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

## Database Connection (MySQL)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservicetask
    username: root
    password: rootuser

  config:
    import:
      - optional:configserver:http://localhost:8888

## Connection Pooling
    hikari:
      ### max connections
      maximum-pool-size: 12
      ### if no connection allocated
      connection-timeout: 20000
      ### life time of sql
      max-lifetime: 1200000
      ### idle connections
      minimum-idle: 5
      ### if no activity then idle
      idle-timeout: 30000
      ### if no activity then idle
      auto-commit: true

## JPA Properties
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        formate_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
      
